---
title: 'Bayesian A/B testing'
output: html_document
---

```{r, message = FALSE}
if (!'conversion.rate' %in% rownames(installed.packages())) {
  library(devtools)
  install_github('chain-rule/conversion-rate', quiet = TRUE, upgrade = 'always')
}

library(conversion.rate)
library(tidyverse)

source('plotting.R')
theme_set(theme_light())
```

```{r}
compute_density <- function(alpha_a, beta_a, alpha_b, beta_b) {
  tibble(Conversion = seq(0, 0.1, length.out = 1000)) %>%
  crossing(Group = c('A', 'B')) %>%
  mutate(Density = dbeta(Conversion,
                         if_else(Group == 'A', alpha_a, alpha_b),
                         if_else(Group == 'A', beta_a, beta_b)))
}
```

```{r}
replication_num <- 10000
day_num <- 21
daily_num <- 1000

alpha_prior_a <- 20
beta_prior_a <- 980

alpha_prior_b <- alpha_prior_a / 10
beta_prior_b <- beta_prior_a / 10

loss_threshold <- 0.01 * alpha_prior_a / (alpha_prior_a + beta_prior_a)
```

## Prior distributions

```{r}
compute_density(alpha_prior_a, beta_prior_a, alpha_prior_b, beta_prior_b) %>%
  ggplot(aes(Conversion, Density, color = Group)) +
  geom_line() +
  theme(legend.title = element_blank())
```

## Simulation results

```{r}
set.seed(2018-12-01)

data <- tibble(replication = seq_len(replication_num)) %>%
  mutate(alpha_prior_a = alpha_prior_a,
         beta_prior_a = beta_prior_a,
         alpha_prior_b = alpha_prior_b,
         beta_prior_b = beta_prior_b) %>%
  simulate(day_num = day_num,
           daily_num = daily_num,
           expected_loss = list(approximate = TRUE),
           greater_probability = list(approximate = TRUE)) %>%
  group_by(replication) %>%
  mutate(passed_any = min(expected_loss) < loss_threshold,
         passed_end = last(expected_loss) < loss_threshold) %>%
  ungroup()

data %>%
  summarize(greater_probability = mean(greater_probability),
            passed_any = mean(passed_any))
```

```{r, warning = FALSE}
data %>%
  filter(replication %in% sample(replication_num, 100)) %>%
  group_by(replication) %>%
  filter(head(cumsum(c(1, expected_loss) < loss_threshold), -1) == 0) %>%
  plot(line = loss_threshold) +
  scale_y_log10() +
  ylab('Posterior expected loss')
```

# Posterior distributions

```{r, message = FALSE}
data_part <- data %>%
  filter(replication %in% sample(replication_num, 1)) %>%
  group_by(replication) %>%
  arrange(day) %>%
  filter(head(cumsum(c(1, expected_loss) < loss_threshold), -1) == 0) %>%
  summarize(day = last(day),
            alpha_posterior_a = last(alpha_posterior_a),
            beta_posterior_a = last(beta_posterior_a),
            alpha_posterior_b = last(alpha_posterior_b),
            beta_posterior_b = last(beta_posterior_b)) %>%
  nest(alpha_posterior_a,
       beta_posterior_a,
       alpha_posterior_b,
       beta_posterior_b) %>%
  mutate(data = map(data, ~ compute_density(.$alpha_posterior_a,
                                            .$beta_posterior_a,
                                            .$alpha_posterior_b,
                                            .$beta_posterior_b))) %>%
  unnest()

data_peak <- data_part %>%
  group_by(replication, Group) %>%
  arrange(desc(Density)) %>%
  top_n(1) %>%
  ungroup() %>%
  mutate(Density = Density + 0.05 * max(Density))

data_part %>%
  ggplot(aes(Conversion, Density, color = Group)) +
  geom_line(aes(group = interaction(replication, Group))) +
  geom_text(data = data_peak, aes(label = day), show.legend = FALSE) +
  theme(legend.title = element_blank())
```
