---
title: 'Bayesian A/B testing'
output: html_document
---

```{r, message = FALSE}
library(devtools)
library(tidyverse)
load_all('simulation')

source('testing.R')
theme_set(theme_light())
```

```{r}
plot <- function(data,
                 line = 0.05,
                 color = 'pass_end',
                 y_aestetic = 'p_value',
                 labels = c('Not significant', 'Significant')) {
  data %>%
    ggplot(aes_string('day', y_aestetic, group = 'replication')) +
    geom_line(aes_string(alpha = color, color = color)) +
    geom_hline(color = 'red', yintercept = line, lty = 2) +
    scale_color_manual(values = c('black', 'red'), labels = labels) +
    scale_alpha_manual(values = c(0.15, 1), labels = labels) +
    labs(color = '', alpha = '') +
    xlab('Day of experiment')
}
```

```{r}
level <- 0.05
day_num = 20
per_day_num <- 10000
replication_num <- 10000
conversion_base <- 0.001
```

# No effect

```{r}
set.seed(2018 - 12 - 01)

data_null <- data_frame(replication = seq_len(replication_num)) %>%
  simulate(day_num = day_num,
           per_day_num = per_day_num,
           rate_a = conversion_base,
           effect_b = 0,
           approximate = TRUE) %>%
  mutate(p_value = vectorized_prop_test(success_num_a,
                                        total_num_a - success_num_a,
                                        success_num_b,
                                        total_num_b - success_num_b)$p.value)
```

### Waiting

```{r}
data_null %>%
  filter(day == day_num) %>%
  { mean(.$p_value < level) }
```

```{r}
data <- data_null %>%
  filter(replication %in% sample(replication_num, 100)) %>%
  group_by(replication) %>%
  mutate(pass_end = last(p_value) < level) %>%
  mutate(pass_anywhere = min(p_value) < level)

data_wait <- data %>%
  filter(day == day_num, p_value < level)

data_wait %>% nrow()
```

```{r}
data %>%
  plot(line = level) +
  geom_point(data = data_wait, color = 'red') +
  ylab('P-value')
```

### Peeking

```{r}
data_peek <- data %>%
  filter(p_value < level) %>%
  slice(1)

data_peek %>% nrow()
```

```{r}
data %>%
  filter(head(cumsum(c(1, p_value) < level), -1) == 0) %>%
  plot(color = 'pass_anywhere', line = level) +
  geom_point(data = data_peek, color = 'red') +
  ylab('P-value')
```

# Negative effect

```{r}
effect_size <- 0.0001
care_threshold <- 0.1 * effect_size

data_negative <- data_frame(replication = seq_len(replication_num)) %>%
  simulate(day_num = day_num,
           per_day_num = per_day_num,
           rate_a = conversion_base,
           effect_b = -effect_size,
           alpha_a = 10,
           alpha_b = 10,
           beta_a = 90,
           beta_b = 90,
           approximate = TRUE)

data <- data_negative %>%
  filter(replication %in% sample(replication_num, 100)) %>%
  group_by(replication, alpha_a) %>%
  mutate(pass_end = last(expected_loss) < care_threshold,
         pass_anywhere = min(expected_loss) < care_threshold)
```

### Waiting

```{r}
data_wait <- data %>%
  filter(day == day_num, expected_loss < care_threshold)

data_wait %>% nrow()
```

```{r}
data %>%
  plot(y_aestetic = 'expected_loss',
       line = care_threshold,
       labels = c('Not passed', 'Passed')) +
  geom_point(data = data_wait, color = 'red') +
  scale_y_log10() +
  ylab('Posterior expected loss')
```

### Peeking

```{r}
data_peek <- data %>%
  filter(expected_loss < care_threshold) %>%
  slice(1)

data_peek %>% nrow()
```

```{r}
data %>%
  filter(head(cumsum(c(1, expected_loss) < care_threshold), -1) == 0) %>%
  plot('pass_anywhere',
       y_aestetic = 'expected_loss',
       line = care_threshold,
       labels = c('Not passed', 'Passed')) +
  geom_point(data = data_peek, color = 'red') +
  scale_y_log10() +
  ylab('Posterior expected loss')
```

## Positive effect

```{r}
data_positive <- data_frame(replication = seq_len(4 * replication_num)) %>%
  mutate(rate_a = rbeta(n(), 100, 99900),
         rate_b = rbeta(n(), 100, 99900),
         effect_b = rate_b - rate_a) %>%
  simulate(day_num = day_num,
           per_day_num = per_day_num,
           alpha_a = 100,
           alpha_b = 100,
           beta_a = 99900,
           beta_b = 99900)

data <- data_positive %>%
  arrange(replication) %>%
  group_by(replication) %>%
  slice(c(which.min(expected_loss), n())) %>%
  mutate(rule = c('Peeking', 'Waiting'))
```

```{r, warning = FALSE}
data %>%
  mutate(loss = pmax(-effect_b, 0)) %>%
  group_by(rule) %>%
  arrange(expected_loss) %>%
  mutate(cumulative_loss = cummean(loss)) %>%
  ggplot(aes(expected_loss, cumulative_loss, color = rule)) +
  geom_line() +
  geom_abline(lty = 2) +
  xlab('Expected loss') +
  ylab('Cumulative loss') +
  scale_x_log10(lim = c(1e-7, 1e-3)) +
  scale_y_log10(lim = c(1e-7, 1e-3)) +
  theme(legend.title = element_blank())
```
