---
title: 'College Majors'
output: html_notebook
---

```{r, message = FALSE}
library(tidyverse)
library(ggrepel)
library(scales)

theme_set(theme_light())
```

```{r, message = FALSE}
data <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-16/recent-grads.csv')
```

```{r}
data <- data %>%
  mutate(Major = str_to_title(Major),
         Major = fct_reorder(Major, Median),
         Major_category = fct_reorder(Major_category, Median)) %>%
  arrange(desc(Median))
```

## What are the highest earning categories?

```{r, dev = 'svg', fig.width = 10}
data %>%
  ggplot(aes(Major_category, Median, fill = Major_category)) +
  geom_boxplot() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format()) +
  theme(legend.position = 'none') +
  labs(x = '') +
  coord_flip()
```

## What are the highest earning majors?

```{r, dev = 'svg', fig.width = 10}
data %>%
  filter(Sample_size >= 100) %>%
  head(20) %>%
  ggplot(aes(Major, Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format()) +
  labs(x = '') +
  coord_flip()
```

## How does gender relate to earnings?

```{r, dev = 'svg', fig.width = 10}
data %>%
  arrange(desc(Total)) %>%
  head(20) %>%
  mutate(Major = fct_reorder(Major, Total)) %>%
  gather(Gender, Number, Men, Women) %>%
  ggplot(aes(Major, Number, fill = Gender)) +
  geom_col() +
  scale_y_continuous(labels = comma_format()) +
  labs(x = '') +
  coord_flip()
```

```{r, dev = 'svg', fig.width = 10}
data %>%
  filter(!is.na(Total)) %>%
  group_by(Major_category) %>%
  summarize(Men = sum(Men),
            Women = sum(Women),
            Total = sum(Total),
            MedianSalary = sum(Median * Sample_size) / sum(Sample_size)) %>%
  mutate(ShareWomen = Women / Total) %>%
  ggplot(aes(ShareWomen, MedianSalary)) +
  geom_point(aes(color = Major_category)) +
  geom_smooth(method = 'lm', alpha = 0.1, color = 'black', size = 0.5) +
  geom_text_repel(aes(label = Major_category), force = 1) +
  scale_y_continuous(labels = dollar_format()) +
  theme(legend.position = 'none')
```

