---
title: 'Baseball'
output: html_document
---

```{r, include = FALSE}
install.packages(readr::read_lines('requirements.txt'))
```

```{r, message = FALSE}
library(Lahman)
library(tidyverse)

theme_set(theme_light())
```

```{r}
level = 0.95

data <- Batting %>%
  filter(AB > 0) %>%
  anti_join(Pitching, by = 'playerID') %>%
  group_by(playerID) %>%
  summarize(H = sum(H), AB = sum(AB)) %>%
  inner_join(Master %>%
               select(playerID, nameFirst, nameLast) %>%
               unite(name, nameFirst, nameLast, sep = ' '),
             by = 'playerID') %>%
  select(name, H, AB)
```

## Point estimation

```{r}
data <- data %>%
  mutate(mean = H / AB)

data %>%
  arrange(desc(mean)) %>%
  head(10)
```

```{r}
parameters <- data %>%
  filter(AB > 500) %>%
  .$mean %>%
  MASS::fitdistr(dbeta,
                 list(shape1 = 1, shape2 = 1),
                 lower = c(0, 0)) %>%
  .$estimate
```

```{r}
data %>%
  filter(AB > 500) %>%
  ggplot(aes(mean)) +
  geom_histogram(aes(y = ..density..), bins = 80) +
  geom_line(data = tibble(x = seq(0.15, 0.4, by = 0.01)) %>%
                     mutate(y = dbeta(x, parameters[1], parameters[2])),
            mapping = aes(x = x, y = y),
            color = 'red',
            size = 1)
```

```{r}
data <- data %>%
  mutate(alpha = H + parameters[1],
         beta = AB - H + parameters[2],
         posterior_mean = alpha / (alpha + beta))
         
data %>%
  arrange(desc(posterior_mean)) %>%
  head(10)
```

## Set estimation

```{r}
data <- data %>%
  nest(H, AB) %>%
  mutate(test = map(data, ~ binom.test(.$H, .$AB, conf.level = level)),
         confidence_lower = map_dbl(test, ~ .$conf.int[1]),
         confidence_upper = map_dbl(test, ~ .$conf.int[2])) %>%
  unnest(data) %>%
  select(-test)
```

```{r}
data <- data %>%
  mutate(credibility_lower = qbeta((1 - level) / 2, alpha, beta),
         credibility_upper = qbeta((1 + level) / 2, alpha, beta))
```

```{r}
data %>%
  sample_n(50) %>%
  arrange(AB) %>%
  mutate(battor = 1:n(),
         confidence = pmap(list(confidence_lower, mean, confidence_upper), c),
         credibility = pmap(list(credibility_lower, posterior_mean, credibility_upper), c)) %>%
  select(battor, confidence, credibility) %>%
  gather(type, interval, confidence, credibility) %>%
  mutate(lower = map_dbl(interval, ~ .x[1]),
         center = map_dbl(interval, ~ .x[2]),
         upper = map_dbl(interval, ~ .x[3])) %>%
  ggplot(aes(battor, center, color = type)) +
  geom_errorbar(aes(ymin = lower, ymax = upper),
                alpha = 0.5) +
  geom_point() +
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = 'bottom')
```

## Hypothesis testing

```{r}
data <- data %>%
  mutate(posterior_error = pbeta(0.3, alpha, beta))
```

```{r}
data %>%
  filter(posterior_error < 1 - level) %>%
  arrange(posterior_error) %>%
  select(name, credibility_lower, posterior_mean, credibility_upper, posterior_error)
```

```{r}
data %>%
  ggplot(aes(posterior_mean, posterior_error, color = AB)) +
  geom_point() +
  geom_hline(yintercept = 0.5, color = 'gray30', linetype = 'dashed') +
  geom_hline(yintercept = 1 - level, color = 'gray30', linetype = 'dashed') +
  geom_vline(xintercept = 0.3, color = 'gray30', linetype = 'dashed')
```

## False discovery rate control

```{r}
data <- data %>%
  arrange(posterior_error)
```

```{r}
data %>%
  head(100) %>%
  .$posterior_error %>%
  sum()
```

```{r}
data %>%
  head(100) %>%
  .$posterior_error %>%
  mean()
```

```{r}
data <- data %>%
  mutate(q = cummean(posterior_error))

data %>%
  filter(q < 1 - level) %>%
  select(name, posterior_mean, posterior_error, q)
```

```{r}
data %>%
  filter(q < 0.25) %>%
  mutate(battors = 1:n()) %>%
  ggplot(aes(q, battors)) +
  geom_line() +
  labs(x = 'Q-value', y = 'Number of battors')
```

## A/B testing

```{r}
candidates <- data %>%
  filter(name %in% c('Hank Aaron', 'Mike Piazza'))

candidates
```

```{r}
compute_beta <- function(player) {
  tibble(x = seq(0.28, 0.33, by = 0.001)) %>%
         mutate(y = dbeta(x, player$alpha, player$beta))
}

candidates %>%
  select(name, alpha, beta) %>%
  nest(alpha, beta) %>%
  mutate(model = map(data, compute_beta)) %>%
  select(-data) %>%
  unnest() %>%
  ggplot(aes(x, y, color = name)) +
  geom_line() +
  labs(x = 'Batting average', y = 'Posterior density')
```

```{r}
compute_superiority <- function(a, b, c, d) {
  j <- seq.int(0, round(c) - 1)
  values <- lbeta(a + j, b + d) - log(d + j) - lbeta(1 + j, d) - lbeta(a, b)
  1 - sum(exp(values))
}

compute_superiority_hat <- function(a, b, c, d) {
  m1 <- a / (a + b)
  m2 <- c / (c + d)
  v1 <- (a * b) / ((a + b) ^ 2 * (a + b + 1))
  v2 <- (c * d) / ((c + d) ^ 2 * (c + d + 1))
  pnorm(0, m2 - m1, sqrt(v1 + v2))
}
```

```{r}
parameters <- list(a = candidates[['alpha']][1],
                   b = candidates[['beta']][1],
                   c = candidates[['alpha']][2],
                   d = candidates[['beta']][2])

do.call(compute_superiority, parameters)
```

```{r}
do.call(compute_superiority_hat, parameters)
```

### Confidence interval

```{r}
prop.test(candidates$H, candidates$AB)
```

### Credible interval

```{r}
compute_credibility_hat <- function(a, b, c, d) {
  m1 <- a / (a + b)
  m2 <- c / (c + d)
  v1 <- a * b / ((a + b) ^ 2 * (a + b + 1))
  v2 <- c * d / ((c + d) ^ 2 * (c + d + 1))
  m_delta <- m2 - m1
  s_delta <- sqrt(v1 + v2)
  tibble(posterior = pnorm(0, m_delta, s_delta),
         estimate = m_delta,
         lower = qnorm((1 - level) / 2, m_delta, s_delta),
         upper = qnorm((1 + level) / 2, m_delta, s_delta))
}
```

```{r}
do.call(compute_credibility_hat, parameters)
```

```{r}
name <- 'Mike Piazza'
names <- c('Hank Aaron')
names <- data %>%
  filter(name != !!name & !name %in% names) %>%
  sample_n(20) %>%
  distinct() %>%
  .$name %>%
  c(names, .)

battor <- data %>%
  filter(name == !!name)

data %>%
  filter(name %in% names) %>%
  select(name, alpha, beta) %>%
  nest(alpha, beta) %>%
  mutate(model = map(data, ~ compute_credibility_hat(battor$alpha,
                                                     battor$beta,
                                                     .$alpha,
                                                     .$beta))) %>%
  select(-data) %>%
  unnest(model) %>%
  mutate(name = fct_reorder(name, estimate)) %>%
  ggplot(aes(name, estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper)) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme(axis.title.y = element_blank())
```

