---
title: 'Baseball'
output: html_document
---

```{r, message = FALSE}
library(Lahman)
library(tidyverse)
```

```{r}
level = 0.95

data <- Batting %>%
  filter(AB > 0) %>%
  anti_join(Pitching, by = 'playerID') %>%
  group_by(playerID) %>%
  summarize(H = sum(H), AB = sum(AB)) %>%
  inner_join(Master %>%
               select(playerID, nameFirst, nameLast) %>%
               unite(name, nameFirst, nameLast, sep = ' '),
             by = 'playerID') %>%
  select(name, H, AB)
```

## Point estimation

```{r}
data <- data %>%
  mutate(mean = H / AB)

data %>%
  arrange(desc(mean)) %>%
  head(10)
```

```{r}
parameters <- data %>%
  filter(AB > 500) %>%
  .$mean %>%
  MASS::fitdistr(dbeta,
                 list(shape1 = 1, shape2 = 1),
                 lower = c(0, 0)) %>%
  .$estimate
```

```{r}
data %>%
  filter(AB > 500) %>%
  ggplot(aes(mean)) +
  geom_histogram(aes(y = ..density..), bins = 80) +
  geom_line(data = tibble(x = seq(0.15, 0.4, by = 0.01)) %>%
                     mutate(y = dbeta(x, parameters[1], parameters[2])),
            mapping = aes(x = x, y = y),
            color = 'red',
            size = 1)
```

```{r}
data <- data %>%
  mutate(alpha = H + parameters[1],
         beta = AB - H + parameters[2],
         posterior_mean = alpha / (alpha + beta))
         
data %>%
  arrange(desc(posterior_mean)) %>%
  head(10)
```

## Set estimation

```{r}
data <- data %>%
  nest(H, AB) %>%
  mutate(test = map(data, ~ binom.test(.$H, .$AB, conf.level = level)),
         confidence_lower = map_dbl(test, ~ .$conf.int[1]),
         confidence_upper = map_dbl(test, ~ .$conf.int[2])) %>%
  unnest(data) %>%
  select(-test)
```

```{r}
data <- data %>%
  mutate(credibility_lower = qbeta((1 - level) / 2, alpha, beta),
         credibility_upper = qbeta((1 + level) / 2, alpha, beta))
```

```{r}
data %>%
  sample_n(50) %>%
  arrange(AB) %>%
  mutate(battor = 1:n(),
         confidence = pmap(list(confidence_lower, mean, confidence_upper), c),
         credibility = pmap(list(credibility_lower, posterior_mean, credibility_upper), c)) %>%
  select(battor, confidence, credibility) %>%
  gather(type, interval, confidence, credibility) %>%
  mutate(lower = map_dbl(interval, ~ .x[1]),
         center = map_dbl(interval, ~ .x[2]),
         upper = map_dbl(interval, ~ .x[3])) %>%
  ggplot(aes(battor, center, color = type)) +
  geom_errorbar(aes(ymin = lower, ymax = upper),
                alpha = 0.5) +
  geom_point() +
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = 'bottom')
```

## Hypothesis testing

```{r}
data <- data %>%
  mutate(posterior_tail = pbeta(0.3, alpha, beta))
```

```{r}
data %>%
  filter(posterior_tail < 1 - level) %>%
  arrange(posterior_tail) %>%
  select(name, credibility_lower, posterior_mean, credibility_upper, posterior_tail)
```

```{r}
data %>%
  ggplot(aes(posterior_mean, posterior_tail, color = AB)) +
  geom_point() +
  geom_hline(yintercept = 0.5, color = 'gray30', linetype = 'dashed') +
  geom_hline(yintercept = 1 - level, color = 'gray30', linetype = 'dashed') +
  geom_vline(xintercept = 0.3, color = 'gray30', linetype = 'dashed')
```

## False discovery rate control

```{r}
data %>%
  arrange(posterior_tail) %>%
  head(100) %>%
  .$posterior_tail %>%
  sum()
```
