---
title: 'Cats versus Dogs'
output: html_notebook
---

```{r, message = FALSE}
library(plotly)
library(tidyverse)
```

```{r}
data <- read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-09-11/cats_vs_dogs.csv') %>%
  select(state, 
         n_households,
         n_pet_households,
         n_cat_households, cat_population,
         n_dog_households, dog_population) %>%
  rename(State = state,
         TotalHouseholds = n_households,
         PetHouseholds = n_pet_households,
         CatHouseholds = n_cat_households,
         DogHouseholds = n_dog_households,
         CatPets = cat_population,
         DogPets = dog_population) %>%
  gather(Key, Value, -State, -TotalHouseholds, -PetHouseholds) %>%
  extract(Key, c('Pet', 'Key'), '(Cat|Dog)(Households|Pets)') %>%
  spread(Key, Value) %>%
  select(State, Pet, Households, Pets, PetHouseholds, TotalHouseholds)
```

## Which States Like Cats the Most?

```{r}
data1 <- data %>%
  group_by(State) %>%
  mutate(CatDogHouseholds = sum(Households),
         CatDogPets = sum(Pets),
         CatHouseholdFraction = sum((Pet == 'Cat') * Households) / CatDogHouseholds,
         CatPetFraction = sum((Pet == 'Cat') * Pets) / CatDogPets) %>%
  ungroup() %>%
  mutate(HouseholdFraction = Households / CatDogHouseholds,
         PetFraction = Pets / CatDogPets)
```

### By Households

```{r, dev = 'svg', fig.height = 3.5, fig.width = 10}
data1 %>%
  filter(CatHouseholdFraction > 0.5) %>%
  mutate(State = fct_reorder(State, (Pet == 'Cat') * HouseholdFraction)) %>%
  ggplot(aes(State, HouseholdFraction, fill = State)) +
  facet_grid(. ~ Pet) +
  geom_col() +
  labs(y = 'Fraction of households with pets') +
  theme(legend.position = 'none',
        axis.title.y = element_blank()) +
  coord_flip()
```

### By Cat and Dog Pets

```{r, dev = 'svg', fig.height = 10, fig.width = 10}
data1 %>%
  filter(CatPetFraction > 0.5 & Pet == 'Cat') %>%
  mutate(State = fct_reorder(State, CatPetFraction)) %>%
  ggplot(aes(State, PetFraction, fill = State)) +
  geom_col() +
  labs(y = 'Fraction of cats among cats and dogs') +
  theme(legend.position = 'none',
        axis.title.y = element_blank()) +
  coord_flip()
```

## Is There a Relation between Cats and Dogs per Households?

```{r, dev = 'svg', fig.height = 6, fig.width = 10}
data %>%
  select(State, Pet, Pets, TotalHouseholds) %>%
  spread(Pet, Pets) %>%
  mutate(CatsPerHousehold = Cat / TotalHouseholds,
         DogsPerHousehold = Dog / TotalHouseholds,
         State = fct_reorder(State, CatsPerHousehold)) %>% {
    ggplot(., aes(CatsPerHousehold, DogsPerHousehold, size = TotalHouseholds)) +
    geom_smooth(method = 'lm', show.legend = FALSE, color = 'gray50', se = FALSE) +
    geom_point(aes(color = State)) +
    labs(x = 'Cats per household', y = 'Dogs per household') +
    guides(color = FALSE, size = guide_legend(title = 'Total households'))
  } %>%
  ggplotly()
```

