---
title: 'Lobaration 2'
output: html_document
---

```{r, message = FALSE}
library(MASS)
library(tidyverse)

theme_set(theme_minimal())
```

```{r}
geom_reference <- function(data, type = 'cdf', binwidth = 1) {
  if (type == 'cdf') {
    stat_ecdf(data = data,
              mapping = aes(x),
              color = 'gray70')
  } else if (type == 'pdf') {
    geom_density(data = data,
                 mapping = aes(x),
                 color = 'gray70')
  } else if (type == 'histogram') {
    geom_histogram(data = data,
                   mapping = aes(x, y = ..count.. / sum(..count..)),
                   binwidth = binwidth,
                   fill = 'gray70')
  }
}
```

```{r}
data <- tibble(x = galaxies / 1000)
```

```{r}
ggplot() +
  geom_reference(data) +
  labs(x = 'Velocity', y = 'Probability')
```

```{r}
ggplot() +
  geom_reference(data, type = 'histogram') +
  labs(x = 'Velocity', y = 'Density')
```

# Direct prior

```{r}
stick_break <- function(l, alpha, beta) {
  q <- rbeta(l, shape1 = alpha, shape2 = beta)
  q <- c(head(q, -1), 1)
  list(p = q * c(1, cumprod(1 - head(q, -1))), q = q)
}

nu_prior <- function(lambda = 1, mu0 = 0, sigma0 = 1) {
  sample_P0 <- function(l) rnorm(l, mean = mu0, sd = sigma0)
  list(sample_P0 = sample_P0, lambda = lambda)
}

nu_posterior <- function(x, lambda = 1, mu0 = 0, sigma0 = 1) {
  prior <- nu_prior(lambda = lambda, mu0 = mu0, sigma0 = sigma0)
  sample_P0 <- function(l) {
    i <- rbernoulli(l, p = lambda / (lambda + length(x)))
    i * prior$sample_P0(l) + (1 - i) * sample(x, l, replace = TRUE)
  }
  list(sample_P0 = sample_P0, lambda = lambda + length(x))
}

sample_DP <- function(l, nu) {
  x <- nu$sample_P0(l)
  p <- stick_break(l, 1, nu$lambda)$p
  tibble(x = x, p = p)
}

plot_distribution <- function(sample, reference) {
  sample <- sample %>%
    arrange(x) %>%
    mutate(p = cumsum(p))
  ggplot() +
    geom_reference(reference) +
    geom_line(data = sample, mapping = aes(x, p)) +
    labs(x = 'Velocity', y = 'Probability')
}
```

```{r, fig.asp = 1}
set.seed(42)

tibble(lambda = c(1, 10, 100, 1000)) %>%
  mutate(data = map(lambda, ~ sample_DP(l = 10000,
                                        nu = nu_prior(lambda = .x,
                                                      mu0 = mean(data$x),
                                                      sigma0 = sd(data$x))))) %>%
  unnest(data) %>%
  mutate(lambda = str_c('Prior volume = ', lambda)) %>%
  group_by(lambda) %>%
  plot_distribution(data) +
  facet_wrap(vars(lambda), ncol = 1)
```

```{r, fig.asp = 1}
set.seed(42)

tibble(lambda = c(1, 10, 100, 1000)) %>%
  mutate(data = map(lambda, ~ sample_DP(l = 10000,
                                        nu = nu_posterior(data$x,
                                                          lambda = .x,
                                                          mu0 = mean(data$x),
                                                          sigma0 = sd(data$x))))) %>%
  unnest(data) %>%
  mutate(lambda = str_c('Prior volume = ', lambda)) %>%
  group_by(lambda) %>%
  plot_distribution(data) +
  facet_wrap(vars(lambda), ncol = 1)
```

# Mixing prior

```{r}
sample_Ptheta_prior <- function(l, mu0 = 0, kappa0 = 1, nu0 = 3, sigma0 = 1) {
  sigma <- sqrt((nu0 * sigma0^2) / rchisq(l, nu0))
  # sigma <- sqrt(1 / rgamma(l, nu0 / 2, nu0 * sigma0^2 / 2))
  mu <- rnorm(l, mu0, sigma / sqrt(kappa0))
  tibble(mu = mu, sigma = sigma)
}

sample_Ptheta_posterior <- function(l, x, mu0 = mean(x), kappa0 = 1, nu0 = 3, sigma0 = sd(x)) {
  n1 <- length(x)
  if (n1 == 0) {
    mu1 <- 0
    ss1 <- 0
  } else {
    mu1 <- mean(x)
    ss1 <- sum((x - mu1)^2)
  }
  sample_Ptheta_prior(
    l = l,
    mu0 = kappa0 / (kappa0 + n1) * mu0 + n1 / (kappa0 + n1) * mu1,
    kappa0 = kappa0 + n1,
    nu0 = nu0 + n1,
    sigma0 = sqrt((nu0 * sigma0^2 + ss1 + kappa0 * n1 / (kappa0 + n1) * (mu1 - mu0)^2) / (nu0 + n1))
  )
}

sample_Plambda_prior <- function(l, alpha0 = 2, beta0 = 0.1) {
  rgamma(l, alpha0, beta0)
}

sample_Plambda_posterior <- function(l, q, alpha0 = 2, beta0 = 0.1) {
  sample_Plambda_prior(
    l = l,
    alpha0 = alpha0 + length(q) - 1,
    beta0 = beta0 - sum(log(head(q, -1)))
  )
}

evaluate_Px <- function(x, theta) {
  dnorm(x, theta$mu, sqrt(theta$sigma))
}

evaluate_Pm_ <- function(draw, grid, type = 'cdf') {
  if (type == 'cdf') {
    method <- pnorm
  } else if (type == 'pdf') {
    method <- dnorm
  } else if (type == 'histogram') {
    method <- dnorm
  }
  bind_cols(draw$theta, tibble(p = draw$stick$p)) %>%
    mutate(.component = row_number()) %>%
    select(.component, everything()) %>%
    mutate(data = map2(mu, sigma, function(mu, sigma) {
                                  tibble(x = grid,
                                         y = method(grid, mu, sigma))
                                  })) %>%
    unnest(data) %>%
    group_by(x) %>%
    summarize(y = sum(p * y), .groups = 'drop')
}

evaluate_Pm <- function(draws, grid, ...) {
  process <- function(i) {
    evaluate_Pm_(draws[[i]], grid, ...) %>%
      mutate(.draw = i) %>%
      select(.draw, everything())
  }
  sapply(1:length(draws), process, simplify = FALSE) %>%
    bind_rows()
}

count_subjects <- function(m, k) {
  n <- rep(0, m)
  k <- as.data.frame(table(k))
  n[as.numeric(levels(k[ , 1]))[k[ , 1]]] <- k[ , 2]
  n
}

update_k <- function(x, state, prior_only = FALSE) {
  m <- length(state$stick$p)
  n <- length(x)
  if (prior_only) {
    x <- rep(x, each = m)
    theta <- state$theta %>% slice(rep(1:m, n))
    p <- matrix(evaluate_Px(x, theta), nrow = m, ncol = n)
    p <- sweep(p, 1, state$stick$p, `*`)
    p <- sweep(p, 2, colSums(p), `/`)
  } else {
    p <- matrix(rep(1 / m, m * n), nrow = m, ncol = n)
  }
  apply(p, 2, function(p) sample(1:m, 1, prob = p))
}

update_stick <- function(x, state, prior_only = FALSE) {
  m <- length(state$stick$p)
  if (prior_only) {
    alpha <- 1
    beta <- state$lambda
  } else {
    n <- count_subjects(m, state$k)
    alpha <- 1 + n
    beta <- state$lambda + sum(n) - cumsum(n)
  }
  stick_break(m, alpha, beta)
}

update_theta <- function(x, state, prior_only = FALSE, ...) {
  m <- length(state$stick$p)
  if (prior_only) {
    sapply(1:m, function(i) sample_Ptheta_prior(1, ...), simplify = FALSE) %>%
      bind_rows()
  } else {
    sapply(1:m, function(i) sample_Ptheta_posterior(1, x[state$k == i], ...),
           simplify = FALSE) %>%
      bind_rows()
  }
}

update_lambda <- function(x, state, prior_only = FALSE, ...) {
  if (prior_only) {
    sample_Plambda_prior(1, ...)
  } else {
    sample_Plambda_posterior(1, state$stick$q, ...)
  }
}

sample_DPM <- function(x, m, l,
                       n0 = 3,
                       mu0 = mean(x),
                       kappa0 = n0,
                       nu0 = n0,
                       sigma0 = sd(x),
                       lambda0 = 1,
                       alpha0 = n0,
                       beta0 = sqrt(n0) / 10,
                       prior_only = FALSE) {
  theta_prior <- list(
    mu0 = mu0,
    kappa0 = kappa0,
    nu0 = nu0,
    sigma0 = sigma0
  )
  lambda_prior <- list(
    alpha0 = alpha0,
    beta0 = beta0
  )
  state <- list(
    k = sample(1:m, length(x), replace = TRUE),
    stick = stick_break(m, 1, lambda0),
    theta = do.call(sample_Ptheta_prior, c(list(m), theta_prior)),
    lambda = lambda0
  )
  draws <- vector('list', l)
  for(i in 1:l) {
    arguments <- list(x, state, prior_only = prior_only)
    state$k <- do.call(update_k, arguments)
    arguments <- list(x, state, prior_only = prior_only)
    state$stick <- do.call(update_stick, arguments)
    arguments <- c(list(x, state, prior_only = prior_only), theta_prior)
    state$theta <- do.call(update_theta, arguments)
    arguments <- c(list(x, state, prior_only = prior_only), lambda_prior)
    state$lambda <- do.call(update_lambda, arguments)
    draws[[i]] <- state
  }
  draws
}

check_predictive <- function(draws, reference, size = 1000, type = 'cdf', ...) {
  grid <- seq(min(reference$x) - 5, to = max(reference$x) + 5, length.out = size)
  sample <- evaluate_Pm(draws, grid, type = type)
  ggplot() +
    geom_reference(reference, type = type, ...) +
    geom_line(data = sample, mapping = aes(x, y, group = .draw), size = 0.25) +
    labs(x = 'Velocity', y = 'Density')
}

summarize_inference <- function(draws, reference, size = 1000, type = 'cdf', ...) {
  grid <- seq(min(reference$x) - 5, to = max(reference$x) + 5, length.out = size)
  sample <- evaluate_Pm(draws, grid, type = type) %>%
    group_by(x) %>%
    summarize(y_mean = mean(y), .groups = 'drop')
  ggplot() +
    geom_reference(reference, type = type, ...) +
    geom_line(data = sample, mapping = aes(x, y_mean), size = 0.25) +
    labs(x = 'Velocity', y = 'Density')
}
```

```{r}
set.seed(42)

sample_Ptheta_prior(1000, mu0 = mean(data$x), sigma0 = sd(data$x)) %>%
  ggplot() +
  geom_vline(xintercept = sd(data$x), color = 'gray70') +
  geom_density(aes(sigma)) +
  labs(x = 'Velocity', y = 'Density')
```

```{r}
set.seed(42)

sample_Ptheta_posterior(1000, data$x) %>%
  ggplot() +
  geom_vline(xintercept = mean(data$x), color = 'gray70') +
  geom_density(aes(mu)) +
  labs(x = 'Velocity', y = 'Density')
```

```{r}
set.seed(42)

draws <- sample_DPM(data$x, 25, 1000, prior_only = TRUE)
check_predictive(sample(tail(draws, length(draws) / 2), 10), data,
                 type = 'histogram')
```

```{r}
set.seed(42)

draws <- sample_DPM(data$x, 25, 1000)
check_predictive(sample(tail(draws, length(draws) / 2), 10), data,
                 type = 'histogram')
```

```{r}
tibble(value = sapply(draws, function(draw) length(unique(draw$k)))) %>%
  mutate(draw = row_number()) %>%
  ggplot(aes(draw, value)) +
  geom_line(size = 0.1) +
  labs(x = 'Iteration', y = 'Position')
```

```{r}
summarize_inference(tail(draws, length(draws) / 2), data,
                    type = 'histogram')
```
